### ISSUE TITLE
Integration jotai-zustand with jotai-molecules

### ISSUE THREAD

**Issue by iamrane** [saasquatch/bunshi#14]
Hi! Im trying to implement jotai-molecules with jotai-zustand.
May I have some guidens how to do it.
I've tried a lot of different ways. But don't really see if they can be tied together.

**Comment by loganvolkers** [comment]
Hi @iamrane thanks for your question and sorry it's taken so long to provide a response.

Can you help me understand more about what you're trying to achieve? 

Zustand and other state technologies work well with `jotai-molecules` which is why we're renaming the package to `bunshi` in our next major version.

For example, here's how you can scope a zustand store to a form.

```ts
import { create } from 'zustand'
import { molecule, createScope } from 'jotai-molecule'

const formScope = createScope<unknown>();

const formScopedBearStore = molecule((_,scope)=>{
   scope(formScope);
   const useBearStore = create((set) => ({
      bears: 0,
      increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
      removeAllBears: () => set({ bears: 0 }),
   }))
  return useBearStore;
});
```

**Comment by dai-shi** [comment]
> which is why we're renaming the package to `bunshi` in our next major version.

😄 

> For example, here's how you can scope a zustand store to a form.

You want to use `createStore` instead of `create`.
(Like, we don't usually pass a custom hook `() => useAtom(fooAtom)` as a context value. It can violate the rules of hooks.)

**Comment by iamrane** [comment]
I starter rethinking how i store my state. Don't use molecules any more. But the above answers seems accurate
